### ISSUE TITLE
[SURE-7630] audit-scanner gets killed by OOM

### ISSUE THREAD

**Issue by flavio** [kubewarden/audit-scanner#194]
### Current Behavior

Given the following environment:
- 150 Deployments, resulting in 300 Pods
- 14 enabled policies

The audit-scanner Pod gets killed by the OOM killer because it consumes more than 2Gb of memory

### Expected Behavior

audit-scanner completes without being killed by OOM

### Steps To Reproduce

1. Use latest version of audit-scanner
2. Create 150 deployments of nginx, with 2 replicas each
3. Run audit-scanner

### Environment

```markdown
- Kubewarden >= 1.8.0
```

### Anything else?

Related issues:

- [x] https://github.com/kubewarden/audit-scanner/pull/201
- [x] https://github.com/kubewarden/audit-scanner/issues/202
- [x] https://github.com/kubewarden/docs/issues/365
- [x] https://github.com/rancher/kubewarden-ui/issues/609
- [x] Update release notes: explain the users they have to delete the old PolicyReports and the old ClusterPolicyReport manually

**Comment by flavio** [comment]
Kubewarden 1.11 is out, this should not happen anymore. Closing
